import NextHead from 'next/head';

export default function Head(props) {
  return (
    <NextHead>
      <title>Nathália S. Caldeira</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo-dark-rounded.ico" />

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      <link
        href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative&family=Cinzel:wght@500&family=DM+Sans&family=Inria+Serif&display=swap"
        rel="stylesheet"
      />
    </NextHead>
  );
}
