import NextHead from 'next/head'

export default function Head(props){
    return (
        <NextHead>
            <title>Nathália S. Caldeira</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.ico" />
        </NextHead>)
}